### ISSUE TITLE
Write the readme in markdown

### ISSUE THREAD

**Issue by anthonyjclark** [MissouriState-ACM/MissouriState-ACM.github.io#6]
I'd recommend that you change the readme to a markdown file (README.md). You'll need to do a "git mv" and then edit the file to use markdown. I'll do this and send a pull request if you'd like.
#7

**Comment by MissouriState-ACM** [comment]
Yeah, if you want to go ahead and send the pull request I will accept it.

**Comment by MissouriState-ACM** [comment]
Thank you for doing that
